name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: pubspec.yaml
    - run: flutter pub get
    - run: flutter build apk --target-platform android-arm64 --split-debug-info=v0.0.1
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: build\app\outputs\flutter-apk\app-release.apk
