name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: 21
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
    - run: flutter pub get
    - run: flutter build apk --target-platform android-arm64 --split-debug-info=v0.0.1
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/app-release.apk"
        tag: $(git rev-parse --short HEAD)

