name: Build APK
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: 21
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
    - run: flutter pub get
    - run: flutter build apk --target-platform android-arm64 --split-debug-info=v0.0.1
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: "build/app/outputs/apk/release/app-release.apk"
  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: apk
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: app-release.apk
